grid_map_filters:

  - name: buffer_normalizer
    type: gridMapFilters/BufferNormalizerFilter

  # Fill holes in the map with inpainting.
  - name: inpaint
    type: gridMapCv/InpaintFilter
    params:
      input_layer: elevation
      output_layer: elevation_inpainted
      radius: 1.0 #0.05

  # Reduce noise with a radial blurring filter.
  #- name: mean_in_radius
  #  type: gridMapFilters/MeanInRadiusFilter
  #  params:
  #    input_layer: elevation_inpainted
  #    output_layer: elevation_smooth
  #    radius: 0.06

 ## Compute surface normals.
#  - name: surface_normals
#    type: gridMapFilters/NormalVectorsFilter
#    params:
#      input_layer: elevation_inpainted
#      output_layers_prefix: normal_vectors_
#      radius: 0.3
#      normal_vector_positive_axis: z

 ## Compute slope from surface normal.
#  - name: slope
#    type: gridMapFilters/MathExpressionFilter
#    params:
#      output_layer: slope
#      expression: acos(normal_vectors_z)
#
 ## Set lower threshold on traversability.
#  - name: lower_threshold
#    type: gridMapFilters/ThresholdFilter
#    params:
#      layer: slope
#      lower_threshold: 0.78
#      set_to: 0
#
#  # Set upper threshold on traversability.
#  - name: upper_threshold
#    type: gridMapFilters/ThresholdFilter
#    params:
#      layer: slope
#      upper_threshold: 0.79
#      set_to: 10 # Other uses: .nan, .inf
